import { useCallback, useEffect, useState } from "react";
import {
  chooseArchitectureOption,
  generateSolutionStrategy,
  getSolutionStrategy,
  type ArchitectureOption,
  type SolutionStrategy,
} from "../lib/backend";

/** How the AI proposes to build one work item: a written strategy, architecture
 *  options to choose between, and the tech stack that follows from the
 *  developer rules. Any rule the AI broke is shown at the top — the rules are
 *  checked against its answer, not assumed to have been obeyed. */
export default function SolutionStrategyPanel({
  workItemId,
  itemTitle,
}: {
  workItemId: number;
  itemTitle: string;
}) {
  const [strategy, setStrategy] = useState<SolutionStrategy | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const refresh = useCallback(async () => {
    try {
      setStrategy(await getSolutionStrategy(workItemId));
      setError(null);
    } catch (e) {
      setError(String(e));
    }
  }, [workItemId]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  async function onGenerate() {
    setBusy(true);
    setError(null);
    setNotice(null);
    try {
      const result = await generateSolutionStrategy(workItemId);
      if (result.blocked) {
        setNotice(
          `The AI stopped rather than guessing: ${result.blocked.reason} ` +
            (result.blocked.whatIsNeeded
              ? `It needs to know: ${result.blocked.whatIsNeeded}`
              : ""),
        );
      } else {
        setNotice(`Strategy generated by ${result.provider} (${result.reason}).`);
      }
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
    }
  }

  const options: ArchitectureOption[] = (() => {
    try {
      return strategy ? JSON.parse(strategy.architectureOptions) : [];
    } catch {
      return [];
    }
  })();

  return (
    <section className="solution-strategy" aria-label={`Solution strategy for ${itemTitle}`}>
      <div className="strategy-head">
        <h3>How to build this</h3>
        <button
          aria-label={`Generate solution strategy for ${itemTitle}`}
          disabled={busy}
          onClick={onGenerate}
        >
          {busy ? "Thinking…" : strategy ? "Regenerate" : "Generate strategy"}
        </button>
      </div>

      {error && <p role="alert">{error}</p>}
      {notice && <p role="status">{notice}</p>}

      {strategy && strategy.ruleViolations.length > 0 && (
        <p className="rule-violation" role="alert">
          This strategy uses technology your rules forbid:{" "}
          <strong>{strategy.ruleViolations.join(", ")}</strong>. Regenerate, or
          relax the rule if it no longer applies.
        </p>
      )}

      {strategy && (
        <>
          <p className="strategy-text">{strategy.strategy}</p>
          {strategy.techStack && (
            <p className="tech-stack">
              <strong>Tech stack:</strong> {strategy.techStack}
            </p>
          )}
          {options.length > 0 && (
            <ul className="architecture-options">
              {options.map((option, index) => (
                <li
                  key={`${option.name}-${index}`}
                  className={strategy.chosenOptionIndex === index ? "chosen" : ""}
                >
                  <strong>{option.name}</strong>{" "}
                  <span className="option-kind">{option.kind}</span>
                  {option.rationale && <p>{option.rationale}</p>}
                  {option.tradeoffs && (
                    <p className="tradeoffs">Trade-offs: {option.tradeoffs}</p>
                  )}
                  <button
                    aria-label={`Choose ${option.name}`}
                    onClick={async () => {
                      await chooseArchitectureOption(
                        workItemId,
                        strategy.chosenOptionIndex === index ? null : index,
                      );
                      await refresh();
                    }}
                  >
                    {strategy.chosenOptionIndex === index ? "Chosen" : "Choose"}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </section>
  );
}
