//! Behind-the-scenes Product scaffolding: when a Product is created with a
//! target folder, the framework's own file layout is generated on disk —
//! a `.CoperativeAI` folder holding a Project_brief.md prefilled from the
//! Product card's answers (the self-hosting Creation Page behaviour).

use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

/// Generates the Product's framework files and returns the scaffold root
/// (`<parent>/<product name>`). The parent folder must already exist
/// (solution security rule: validate paths before writing).
pub fn scaffold_product(parent_dir: &str, product_name: &str, answers_json: &str) -> Result<String, String> {
    let parent = Path::new(parent_dir);
    if !parent.is_dir() {
        return Err(format!(
            "the chosen folder is not an existing directory: {parent_dir}"
        ));
    }
    let safe_name = sanitize_name(product_name);
    if safe_name.is_empty() {
        return Err("the Product name doesn't produce a usable folder name".into());
    }
    let root: PathBuf = parent.join(&safe_name);
    let framework_dir = root.join(".CoperativeAI");
    let claude_only = framework_dir.join("claude-only");
    fs::create_dir_all(&claude_only)
        .map_err(|e| format!("could not create the Product's folders: {e}"))?;

    let brief = render_project_brief(product_name, answers_json);
    fs::write(framework_dir.join("Project_brief.md"), brief)
        .map_err(|e| format!("could not write Project_brief.md: {e}"))?;

    let readme = format!(
        "# {product_name}\n\nThis folder was scaffolded by CoperativeAI.\n\n\
         - `.CoperativeAI/Project_brief.md` — the Product's brief, prefilled from the answers given in the app. Developers complete Part 2.\n\
         - `.CoperativeAI/claude-only/` — where the AI's translated specs and code map live.\n\n\
         Each solution created for this Product gets its own folder beside this file.\n"
    );
    fs::write(root.join("README.md"), readme)
        .map_err(|e| format!("could not write README.md: {e}"))?;

    Ok(root.to_string_lossy().into_owned())
}

fn sanitize_name(name: &str) -> String {
    name.trim()
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else if c == ' ' { '-' } else { '_' })
        .collect::<String>()
        .trim_matches(['-', '_'])
        .to_string()
}

fn answer(answers: &Value, key: &str) -> String {
    answers
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .trim()
        .to_string()
}

/// Renders the framework's project-brief form with the Product's answers
/// filled into the Product parts (Part 1 + Part 3); Part 2 stays for the
/// developers to answer.
fn render_project_brief(product_name: &str, answers_json: &str) -> String {
    let answers: Value = serde_json::from_str(answers_json).unwrap_or(Value::Null);
    format!(
        "---\nform: project-brief\nproject: \"{product_name}\"\nstatus: filled            # blank | filled | approved\n---\n\n\
# Project Brief — {product_name}\n\n\
> Generated by CoperativeAI from the Product card's answers. Lines starting with `>` are guidance; everything else is the answer.\n\n\
---\n\n\
## Part 1 — The Idea *(Product answers this)*\n\n\
### purpose — In one or two sentences, what is the purpose of this software?\n{purpose}\n\n\
### problem — What problem does it solve, and for whom?\n{problem}\n\n\
### users — Who will use this software?\n{users}\n\n\
### apps-you-like — Are there any apps or websites you like?\n{apps_you_like}\n\n\
### apps-to-avoid — Are there any apps or websites you want to avoid copying?\n{apps_to_avoid}\n\n\
---\n\n\
## Part 2 — How Should We Build the Solution(s) *(Developers answer this)*\n\n\
### platforms — What platforms would this development need to run on?\n\n\
### repo-structure — Is this a single repo or multi purpose repo?\n\n\
### solutions — List each solution and where its code lives.\n\n\
### dev-rules — Software development rules for the codebase.\n\n\
### roles — List the roles or claims used across the application.\n\n\
### hosting — What technology will host these solutions?\n\n\
### database-technology — What database technology will the solution(s) use?\n\n\
### environments — What environments will this project have, and which may the AI deploy to?\n\n\
### infrastructure-policy — Who creates infrastructure, and with what tool? Where do secrets live?\n\n\
---\n\n\
## Part 3 — Look & Feel *(Product answers this)*\n\n\
### designs — Do you have any designs, sketches, screenshots, or examples?\n{designs}\n",
        purpose = answer(&answers, "purpose"),
        problem = answer(&answers, "problem"),
        users = answer(&answers, "users"),
        apps_you_like = answer(&answers, "appsYouLike"),
        apps_to_avoid = answer(&answers, "appsToAvoid"),
        designs = answer(&answers, "designs"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_parent(name: &str) -> String {
        let dir = std::env::temp_dir().join(format!("coperativeai-scaffold-{name}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir.to_string_lossy().into_owned()
    }

    #[test]
    fn scaffolds_the_framework_layout_with_prefilled_brief() {
        let parent = temp_parent("layout");
        let answers = r#"{"purpose":"Sell things","problem":"Shopping is hard","users":"Shoppers","designs":"Minimal"}"#;
        let root = scaffold_product(&parent, "Shop App", answers).expect("scaffold");

        let brief = std::fs::read_to_string(
            Path::new(&root).join(".CoperativeAI").join("Project_brief.md"),
        )
        .expect("brief exists");
        assert!(brief.contains("project: \"Shop App\""));
        assert!(brief.contains("Sell things"));
        assert!(brief.contains("Shopping is hard"));
        assert!(brief.contains("Minimal"));
        assert!(brief.contains("Part 2 — How Should We Build"));

        assert!(Path::new(&root).join(".CoperativeAI").join("claude-only").is_dir());
        assert!(Path::new(&root).join("README.md").is_file());
    }

    #[test]
    fn rejects_a_nonexistent_parent_folder() {
        let result = scaffold_product("C:/definitely/not/real-xyz", "Shop App", "{}");
        assert!(result.is_err());
    }

    #[test]
    fn product_names_become_safe_folder_names() {
        let parent = temp_parent("names");
        let root = scaffold_product(&parent, "  Shop / App?  ", "{}").expect("scaffold");
        assert!(root.ends_with("Shop-_-App"), "got: {root}");
        assert!(Path::new(&root).is_dir());
    }

    #[test]
    fn missing_answers_render_as_blank_not_errors() {
        let parent = temp_parent("blank");
        let root = scaffold_product(&parent, "Bare", "{}").expect("scaffold");
        let brief = std::fs::read_to_string(
            Path::new(&root).join(".CoperativeAI").join("Project_brief.md"),
        )
        .expect("brief");
        assert!(brief.contains("### purpose"));
    }
}
