//! Emitting the framework's own files from what the app holds.
//!
//! Until app data becomes `.md`/JSON on disk, nothing done in the app is
//! governed by the framework — the briefs are the source of truth Claude reads,
//! and the app was only ever writing the initial Project_brief. This closes
//! that gap: Solutions become solution specs, planned features become page
//! briefs, and both sit beside the Product's scaffold.
//!
//! **Nothing here overwrites a hand edit.** Every write is checked against the
//! hash recorded when the app last wrote that file; if the file on disk has
//! changed since, it is reported as a conflict and left exactly as it is. A
//! file the app has never written is also left alone — not being ours is reason
//! enough not to touch it.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

/// One file to write, relative to the Product's scaffold root.
#[derive(Debug, Clone, PartialEq)]
pub struct EmitFile {
    pub rel_path: String,
    pub contents: String,
}

/// What happened to each file.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EmitReport {
    pub written: Vec<String>,
    /// Already identical — no write needed.
    pub unchanged: Vec<String>,
    /// Changed on disk since we wrote it (or never ours): left untouched.
    pub conflicts: Vec<String>,
}

/// FNV-1a over the content. Change detection, not cryptography: it only has to
/// answer "is this byte-for-byte what we wrote?", and being dependency-free and
/// stable across Rust versions matters more here than collision resistance.
/// (`DefaultHasher` was rejected precisely because it is not stable — a
/// toolchain upgrade would make every file look hand-edited.)
pub fn content_hash(contents: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in contents.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Renders a Solution's spec. Mirrors `template/_forms/application-spec.json`;
/// the answers map holds whatever the Solution card collected.
pub fn solution_spec(
    solution_name: &str,
    solution_type: &str,
    answers_json: &str,
    product_name: &str,
    github_url: Option<&str>,
) -> String {
    let answers: serde_json::Value =
        serde_json::from_str(answers_json).unwrap_or(serde_json::Value::Null);
    let get = |key: &str| -> String {
        answers
            .get(key)
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string()
    };
    let spec = serde_json::json!({
        "form": "application-spec",
        "solutionName": solution_name,
        "solutionType": solution_type,
        "status": "filled",
        "generatedBy": "CoperativeAI",
        "product": product_name,
        "repository": github_url.unwrap_or(""),
        "core": {
            "purpose": { "question": "What is the purpose of this solution?", "answer": get("purpose") },
            "hosting": { "question": "Where will it be hosted, deployed, or distributed?", "answer": get("hosting") },
            "language": { "question": "What language will it use?", "answer": get("language") },
            "frameworks": { "question": "What frameworks, libraries, or UI toolkit should it use?", "answer": get("frameworks") }
        }
    });
    // Pretty-printed with a trailing newline so a human diff is readable and
    // the file matches what an editor would save.
    format!("{}\n", serde_json::to_string_pretty(&spec).expect("spec serialises"))
}

/// Renders a page brief for a planned feature, following `template/_forms/page.md`.
pub fn page_brief(
    feature_title: &str,
    description: Option<&str>,
    product_name: &str,
    deliverable: Option<&str>,
) -> String {
    let description = description.unwrap_or("").trim();
    let mut brief = format!(
        "---\nform: page-brief\npage: \"{feature_title}\"\nsolution: \"{product_name}\"\nstatus: filled\n---\n\n\
         # Page Brief — {feature_title}\n\n\
         > Generated by CoperativeAI from the planning board. Edit freely — the app \
         detects your changes and will not overwrite them.\n\n---\n\n\
         ## Part 1 — What This Page Is For\n\n### why-exists — Why does this page exist?\n"
    );
    if description.is_empty() {
        brief.push_str(
            "_No description was given on the work item. Add one here, or on the board._\n",
        );
    } else {
        brief.push_str(&format!("{description}\n"));
    }
    if let Some(deliverable) = deliverable {
        brief.push_str(&format!(
            "\nThis feature is part of the **{deliverable}** deliverable.\n"
        ));
    }
    brief.push_str(
        "\n---\n\n## Part 2 — What It Should Do\n\n\
         ### actions — What should someone be able to do on this page?\n\n\
         ### look — What should it look like?\n\n\
         ### information — What information does this page show or collect?\n\n\
         ---\n\n## Part 3 — Building Details\n\n\
         ### data-stored — What information needs to be stored?\n\n\
         ### tests — How will we know it works?\n\n\
         ---\n\n## Part 4 — changes-over-time\n\n\
         > Add a bullet each time you come back to improve the page.\n",
    );
    brief
}

/// Filesystem-safe file stem from a title.
pub fn safe_stem(title: &str) -> String {
    let stem: String = title
        .trim()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else if c == ' ' {
                '-'
            } else {
                '_'
            }
        })
        .collect();
    stem.trim_matches(['-', '_']).to_lowercase()
}

/// Writes the files under `root`, respecting hand edits.
///
/// `known` maps a relative path to the hash recorded when the app last wrote
/// it. A file is only overwritten when what is on disk still matches that hash.
pub fn write_files(
    root: &str,
    files: &[EmitFile],
    known: &HashMap<String, String>,
) -> Result<(EmitReport, Vec<(String, String)>), String> {
    let root_path = Path::new(root);
    if !root_path.is_dir() {
        return Err(format!(
            "the Product's folder no longer exists: {root} — re-create it or set the folder again"
        ));
    }
    let mut report = EmitReport::default();
    // (relPath, hash) pairs the caller should record after a successful write.
    let mut recorded = Vec::new();

    for file in files {
        let target = root_path.join(&file.rel_path);
        let new_hash = content_hash(&file.contents);

        if target.exists() {
            let on_disk = fs::read_to_string(&target)
                .map_err(|e| format!("could not read {}: {e}", file.rel_path))?;
            let disk_hash = content_hash(&on_disk);
            match known.get(&file.rel_path) {
                // Untouched since we wrote it → safe to update.
                Some(recorded_hash) if *recorded_hash == disk_hash => {
                    if disk_hash == new_hash {
                        report.unchanged.push(file.rel_path.clone());
                        continue;
                    }
                }
                // Either edited by hand, or a file we never wrote. Leave it.
                _ => {
                    report.conflicts.push(file.rel_path.clone());
                    continue;
                }
            }
        }

        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("could not create {}: {e}", parent.display()))?;
        }
        fs::write(&target, &file.contents)
            .map_err(|e| format!("could not write {}: {e}", file.rel_path))?;
        report.written.push(file.rel_path.clone());
        recorded.push((file.rel_path.clone(), new_hash));
    }
    Ok((report, recorded))
}

/// Writes files the app **owns and regenerates**, overwriting unconditionally.
///
/// Separate from `write_files` on purpose. That function protects things a
/// person authors, where an edit must never be lost. A capability pack is the
/// opposite: it is derived from the Product's current rules, so an edited pack
/// is a stale pack, and keeping it would bind a model to rules that no longer
/// apply. Using the wrong one of these two functions is the kind of mistake
/// that is invisible until someone loses work, hence the different names.
/// Turns a Product's design assets into files under `design/`.
///
/// This is not a nicety — it is the **only** route design tokens have into
/// Figma on any plan below Enterprise, because the Variables REST API is
/// Enterprise-only. The error message for a refused push points here by name,
/// so this function is what makes that message true.
///
/// Pure, so the layout is tested without touching a disk.
pub fn design_files(assets: &[(String, String, String)]) -> Vec<EmitFile> {
    // (kind, name, content)
    let mut files = Vec::new();
    let mut flows = String::new();
    let mut components = String::new();
    let mut brand = String::new();
    let mut campaigns = String::new();
    let mut launch = String::new();
    let mut messaging = String::new();

    for (kind, name, content) in assets {
        match kind.as_str() {
            "campaign" => {
                campaigns.push_str(&format!("## {name}\n\n{content}\n\n"));
                continue;
            }
            "launchPlan" => {
                launch.push_str(&format!("## {name}\n\n{content}\n\n"));
                continue;
            }
            "messaging" => {
                messaging.push_str(&format!("## {name}\n\n{content}\n\n"));
                continue;
            }
            _ => {}
        }
        match kind.as_str() {
            // Each token set becomes its own file: "Core" is the common case
            // and lands at design/tokens.json, which is the name the Figma
            // failure message tells people to look for.
            "tokens" => {
                let stem = safe_stem(name);
                let rel_path = if stem == "core" {
                    "design/tokens.json".to_string()
                } else {
                    format!("design/tokens-{stem}.json")
                };
                files.push(EmitFile { rel_path, contents: content.clone() });
            }
            "uiFlow" => {
                flows.push_str(&format!("## {name}\n\n```mermaid\n{content}\n```\n\n"));
            }
            "componentDiagram" => {
                components.push_str(&format!("## {name}\n\n```mermaid\n{content}\n```\n\n"));
            }
            _ => {
                brand.push_str(&format!("## {name}\n\n{content}\n\n"));
            }
        }
    }

    // Mermaid goes inside fences here, unlike in the database, because these
    // files are read by people and by Markdown renderers rather than by the
    // validator.
    for (rel_path, heading, body) in [
        ("design/ui-flows.md", "# User flows", flows),
        ("design/components.md", "# Components", components),
        ("design/brand.md", "# Brand", brand),
        ("marketing/campaigns.md", "# Campaign ideas", campaigns),
        ("marketing/launch-plan.md", "# Launch plan", launch),
        ("marketing/messaging.md", "# Messaging", messaging),
    ] {
        if !body.trim().is_empty() {
            files.push(EmitFile {
                rel_path: rel_path.to_string(),
                contents: format!("{heading}\n\n> Generated by CoperativeAI.\n\n{body}"),
            });
        }
    }
    files
}

pub fn write_generated(root: &str, files: &[EmitFile]) -> Result<Vec<String>, String> {
    let root_path = Path::new(root);
    if !root_path.is_dir() {
        return Err(format!("the Product's folder no longer exists: {root}"));
    }
    let mut written = Vec::new();
    for file in files {
        let target = root_path.join(&file.rel_path);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("could not create {}: {e}", parent.display()))?;
        }
        fs::write(&target, &file.contents)
            .map_err(|e| format!("could not write {}: {e}", file.rel_path))?;
        written.push(file.rel_path.clone());
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The Figma failure message tells people to look for `design/tokens.json`.
    /// If the emitted name ever drifts from that, the message becomes a lie —
    /// and on any plan below Enterprise it is the *only* route tokens have into
    /// Figma, so the promise has to hold.
    #[test]
    fn the_core_token_set_lands_at_the_path_the_figma_error_promises() {
        let assets = vec![(
            "tokens".to_string(),
            "Core".to_string(),
            // r##"…"## because a hex colour contains `"#`
            r##"{"colour":{"primary":"#1f6feb"}}"##.to_string(),
        )];
        let files = design_files(&assets);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].rel_path, "design/tokens.json");
        assert!(files[0].contents.contains("1f6feb"));

        // and the message that points there still says so
        let message = crate::figma::explain_for_test(403, "write variables");
        assert!(message.contains("design/tokens.json"));
    }

    #[test]
    fn a_second_token_set_gets_its_own_file_rather_than_overwriting_core() {
        let assets = vec![
            ("tokens".into(), "Core".into(), "{}".into()),
            ("tokens".into(), "Dark mode".into(), "{}".into()),
        ];
        let paths: Vec<String> = design_files(&assets).into_iter().map(|f| f.rel_path).collect();
        assert_eq!(paths, vec!["design/tokens.json", "design/tokens-dark-mode.json"]);
    }

    /// Mermaid is stored bare (the validator wants it that way) but written
    /// fenced, because these files are read by people and Markdown renderers.
    #[test]
    fn flows_and_components_are_grouped_into_fenced_markdown() {
        let assets = vec![
            ("uiFlow".into(), "Sign-up".into(), "flowchart TD\n  A-->B".into()),
            ("uiFlow".into(), "Checkout".into(), "flowchart TD\n  C-->D".into()),
            ("componentDiagram".into(), "Shell".into(), "graph LR\n  X-->Y".into()),
            ("brandGuidelines".into(), "Voice".into(), "Warm and plain.".into()),
        ];
        let files = design_files(&assets);
        let by_path = |p: &str| {
            files.iter().find(|f| f.rel_path == p).unwrap_or_else(|| panic!("missing {p}")).contents.clone()
        };

        let flows = by_path("design/ui-flows.md");
        assert!(flows.contains("## Sign-up") && flows.contains("## Checkout"));
        assert!(flows.contains("```mermaid\nflowchart TD"));
        assert!(by_path("design/components.md").contains("graph LR"));
        assert!(by_path("design/brand.md").contains("Warm and plain."));
    }

    #[test]
    fn marketing_artefacts_land_under_their_own_folder() {
        let assets = vec![
            ("campaign".into(), "Forum launch".into(), "Post where the users are.".into()),
            ("campaign".into(), "Newsletter".into(), "Monthly.".into()),
            ("launchPlan".into(), "Q3".into(), "Soft launch first.".into()),
            ("messaging".into(), "Core".into(), "Plain words.".into()),
        ];
        let files = design_files(&assets);
        let by_path = |p: &str| {
            files.iter().find(|f| f.rel_path == p).unwrap_or_else(|| panic!("missing {p}")).contents.clone()
        };

        let campaigns = by_path("marketing/campaigns.md");
        assert!(campaigns.contains("## Forum launch") && campaigns.contains("## Newsletter"));
        assert!(by_path("marketing/launch-plan.md").contains("Soft launch"));
        assert!(by_path("marketing/messaging.md").contains("Plain words."));
        // and nothing marketing leaks into the design files
        assert!(!files.iter().any(|f| f.rel_path.starts_with("design/")));
    }

    /// An empty section must not produce an empty file — a `brand.md` that says
    /// nothing is worse than no brand.md.
    #[test]
    fn sections_with_nothing_in_them_are_not_written() {
        let files = design_files(&[("uiFlow".into(), "Only flow".into(), "flowchart TD\n A-->B".into())]);
        let paths: Vec<&str> = files.iter().map(|f| f.rel_path.as_str()).collect();
        assert_eq!(paths, vec!["design/ui-flows.md"]);
    }

    fn temp_dir(name: &str) -> String {
        let dir = std::env::temp_dir().join(format!("coperativeai-emit-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("create temp dir");
        dir.to_string_lossy().into_owned()
    }

    fn file(path: &str, contents: &str) -> EmitFile {
        EmitFile {
            rel_path: path.into(),
            contents: contents.into(),
        }
    }

    #[test]
    fn the_hash_is_stable_and_distinguishes_content() {
        assert_eq!(content_hash("hello"), content_hash("hello"));
        assert_ne!(content_hash("hello"), content_hash("hello "));
    }

    #[test]
    fn a_solution_spec_carries_the_cards_answers() {
        let spec = solution_spec(
            "Shop API",
            "api",
            r#"{"purpose":"serve the shop","language":"Rust"}"#,
            "Shop App",
            Some("https://github.com/me/shop-api"),
        );
        assert!(spec.contains("\"solutionName\": \"Shop API\""));
        assert!(spec.contains("serve the shop"));
        assert!(spec.contains("Rust"));
        assert!(spec.contains("https://github.com/me/shop-api"));
        // valid JSON, not just a string that looks like it
        serde_json::from_str::<serde_json::Value>(&spec).expect("valid JSON");
    }

    #[test]
    fn a_solution_spec_survives_unparseable_answers() {
        let spec = solution_spec("API", "api", "{not json", "Shop App", None);
        serde_json::from_str::<serde_json::Value>(&spec).expect("still valid JSON");
    }

    #[test]
    fn a_page_brief_uses_the_features_description_and_deliverable() {
        let brief = page_brief("Checkout", Some("One-page checkout"), "Shop App", Some("MVP"));
        assert!(brief.contains("page: \"Checkout\""));
        assert!(brief.contains("One-page checkout"));
        assert!(brief.contains("**MVP** deliverable"));
    }

    #[test]
    fn a_page_brief_says_so_when_the_feature_has_no_description() {
        let brief = page_brief("Checkout", None, "Shop App", None);
        assert!(brief.contains("No description was given"));
    }

    #[test]
    fn titles_become_filesystem_safe_stems() {
        assert_eq!(safe_stem("Checkout flow"), "checkout-flow");
        assert_eq!(safe_stem("  Payments/Refunds  "), "payments_refunds");
        assert_eq!(safe_stem("API"), "api");
    }

    #[test]
    fn first_emit_writes_every_file() {
        let root = temp_dir("first");
        let files = vec![file("a/spec.json", "{}"), file("pages/b.md", "# B")];
        let (report, recorded) = write_files(&root, &files, &HashMap::new()).expect("emit");
        assert_eq!(report.written.len(), 2);
        assert!(report.conflicts.is_empty());
        assert_eq!(recorded.len(), 2);
        assert!(Path::new(&root).join("a/spec.json").exists());
    }

    #[test]
    fn an_unchanged_file_is_not_rewritten() {
        let root = temp_dir("unchanged");
        let files = vec![file("spec.json", "{}")];
        let (_, recorded) = write_files(&root, &files, &HashMap::new()).expect("first");
        let known: HashMap<String, String> = recorded.into_iter().collect();

        let (report, recorded) = write_files(&root, &files, &known).expect("second");
        assert_eq!(report.unchanged, vec!["spec.json".to_string()]);
        assert!(report.written.is_empty());
        assert!(recorded.is_empty());
    }

    #[test]
    fn a_file_we_wrote_and_still_own_is_updated() {
        let root = temp_dir("update");
        let (_, recorded) =
            write_files(&root, &[file("spec.json", "{}")], &HashMap::new()).expect("first");
        let known: HashMap<String, String> = recorded.into_iter().collect();

        let (report, _) =
            write_files(&root, &[file("spec.json", "{\"v\":2}")], &known).expect("second");
        assert_eq!(report.written, vec!["spec.json".to_string()]);
        assert_eq!(
            fs::read_to_string(Path::new(&root).join("spec.json")).expect("read"),
            "{\"v\":2}"
        );
    }

    /// The property this whole module exists for.
    #[test]
    fn a_hand_edited_file_is_reported_and_left_exactly_as_it_is() {
        let root = temp_dir("conflict");
        let (_, recorded) =
            write_files(&root, &[file("spec.json", "{}")], &HashMap::new()).expect("first");
        let known: HashMap<String, String> = recorded.into_iter().collect();

        let path = Path::new(&root).join("spec.json");
        fs::write(&path, "{\"edited\":\"by hand\"}").expect("hand edit");

        let (report, recorded) =
            write_files(&root, &[file("spec.json", "{\"v\":2}")], &known).expect("second");
        assert_eq!(report.conflicts, vec!["spec.json".to_string()]);
        assert!(report.written.is_empty());
        assert!(recorded.is_empty(), "a conflict must not update the record");
        assert_eq!(
            fs::read_to_string(&path).expect("read"),
            "{\"edited\":\"by hand\"}",
            "the hand edit must survive untouched"
        );
    }

    /// A file the app never wrote is not ours to replace, even on a first emit.
    #[test]
    fn a_pre_existing_file_we_never_wrote_is_a_conflict() {
        let root = temp_dir("preexisting");
        let path = Path::new(&root).join("spec.json");
        fs::write(&path, "someone else's file").expect("write");

        let (report, _) =
            write_files(&root, &[file("spec.json", "{}")], &HashMap::new()).expect("emit");
        assert_eq!(report.conflicts, vec!["spec.json".to_string()]);
        assert_eq!(fs::read_to_string(&path).expect("read"), "someone else's file");
    }

    /// A pack is derived from the Product's current rules, so an edited pack is
    /// a stale one and must be replaced — the opposite of a brief.
    #[test]
    fn generated_files_overwrite_without_asking() {
        let root = temp_dir("generated");
        write_generated(&root, &[file("packs/m/system.md", "v1")]).expect("first");
        let path = Path::new(&root).join("packs/m/system.md");
        fs::write(&path, "hand edited").expect("edit");

        let written = write_generated(&root, &[file("packs/m/system.md", "v2")]).expect("second");
        assert_eq!(written, vec!["packs/m/system.md".to_string()]);
        assert_eq!(fs::read_to_string(&path).expect("read"), "v2");
    }

    #[test]
    fn a_missing_root_is_reported_rather_than_created() {
        let missing = std::env::temp_dir().join("coperativeai-emit-does-not-exist-xyz");
        let err = write_files(&missing.to_string_lossy(), &[file("a.md", "x")], &HashMap::new())
            .expect_err("must fail");
        assert!(err.contains("no longer exists"), "got: {err}");
    }
}
